In [2]:
import pandas as pd

# Dataset 1: CarWale specs (price, engine, body type)
df1 = pd.read_csv("../data/raw/shrey_car_dataset.csv")

# Dataset 2: Ratings dataset (mileage, safety, power)
df2 = pd.read_csv("../data/raw/final_cars_dataset.csv")

print("Dataset 1 shape:", df1.shape)
print("Dataset 2 shape:", df2.shape)

Dataset 1 shape: (1276, 16)
Dataset 2 shape: (248, 8)

In [3]:
print("=== Dataset 1 (specs) columns ===")
print(df1.columns.tolist())
print()
df1.head()

=== Dataset 1 (specs) columns ===
['Make', 'Model', 'Variant', 'Ex-Showroom_Price', 'Displacement', 'Cylinders', 'Fuel_Tank_Capacity', 'Fuel_Type', 'Height', 'Length', 'Width', 'Body_Type', 'Seating_Capacity', 'Type', 'Power.1', 'Torque.1']

,Make,Model,Variant,Ex-Showroom_Price,Displacement,Cylinders,Fuel_Tank_Capacity,Fuel_Type,Height,Length,Width,Body_Type,Seating_Capacity,Type,Power.1,Torque.1
0,Hyundai,Santro,Era Mt,"₹ 429,990.000000000000000",1086,4,35.0,Petrol,1560,3610.0,1645,Hatchback,5,Manual,69.0,99.04
1,Hyundai,Santro,Magna Mt,"₹ 503,990.000000000000000",1086,4,35.0,Petrol,1560,3610.0,1645,Hatchback,5,Manual,69.0,99.04
2,Hyundai,Santro,Magna Mt Cng,"₹ 547,990.000000000000000",1086,4,35.0,CNG,1560,3610.0,1645,Hatchback,5,Manual,59.0,99.04
3,Hyundai,Santro,Magna Amt,"₹ 530,990.000000000000000",1086,4,35.0,Petrol,1560,3610.0,1645,Hatchback,5,AMT,69.0,10.10
4,Hyundai,Santro,Sportz Mt,"₹ 512,990.000000000000000",1086,4,35.0,Petrol,1560,3610.0,1645,Hatchback,5,Manual,69.0,10.10

In [4]:
print("=== Dataset 2 (ratings) columns ===")
print(df2.columns.tolist())
print()
df2.head()

=== Dataset 2 (ratings) columns ===
['Brand', 'Car_Name', 'Price_Lakhs', 'Rating', 'Safety_Stars', 'Mileage_kmpl', 'Power_BHP', 'Sales_FY2024']

,Brand,Car_Name,Price_Lakhs,Rating,Safety_Stars,Mileage_kmpl,Power_BHP,Sales_FY2024
0,Maruti Suzuki,Maruti Brezza,8.69,4.5,4.0,21.0,94.5,169897.0
1,Maruti Suzuki,Maruti Fronx,7.54,4.6,3.0,24.0,87.5,134735.0
2,Maruti Suzuki,Maruti Swift,6.49,4.6,2.0,28.0,74.5,195321.0
3,Maruti Suzuki,Maruti Dzire,6.84,4.7,5.0,28.5,74.5,164517.0
4,Maruti Suzuki,Maruti Baleno,6.70,4.5,4.0,26.0,82.0,195607.0

In [5]:
columns.tolist()

NameError: name 'columns' is not defined

In [6]:
# Dataset 1: Make + Model ko combine karke ek match-key banao
df1['match_key'] = (df1['Make'] + ' ' + df1['Model']).str.lower().str.strip()

# Dataset 2: Car_Name already "Brand Model" jaisa hai, seedha use karo
df2['match_key'] = df2['Car_Name'].str.lower().str.strip()

# Kitne unique match keys dono me hain
print("Dataset 1 unique match_keys:", df1['match_key'].nunique())
print("Dataset 2 unique match_keys:", df2['match_key'].nunique())

# Kitne overlap kar rahe hain (direct exact match)
common = set(df1['match_key']) & set(df2['match_key'])
print("Directly matching models:", len(common))

Dataset 1 unique match_keys: 263
Dataset 2 unique match_keys: 248
Directly matching models: 67

In [7]:
# Jo Dataset 2 ke match_keys direct match nahi hue unmein se kuch dekho
unmatched = df2[~df2['match_key'].isin(df1['match_key'])]
print(unmatched[['Brand', 'Car_Name', 'match_key']].head(15))

            Brand             Car_Name            match_key
0   Maruti Suzuki        Maruti Brezza        maruti brezza
1   Maruti Suzuki         Maruti Fronx         maruti fronx
2   Maruti Suzuki         Maruti Swift         maruti swift
3   Maruti Suzuki         Maruti Dzire         maruti dzire
4   Maruti Suzuki        Maruti Baleno        maruti baleno
5   Maruti Suzuki  Maruti Grand Vitara  maruti grand vitara
6   Maruti Suzuki       Maruti Wagon R       maruti wagon r
7   Maruti Suzuki      Maruti Alto K10      maruti alto k10
8   Maruti Suzuki        Maruti Ertiga        maruti ertiga
9   Maruti Suzuki           Maruti XL6           maruti xl6
10  Maruti Suzuki       Maruti Celerio       maruti celerio
11  Maruti Suzuki         Maruti Jimny         maruti jimny
12  Maruti Suzuki         Maruti Ignis         maruti ignis
13  Maruti Suzuki      Maruti S-Presso      maruti s-presso
14  Maruti Suzuki          Maruti Ciaz          maruti ciaz

In [8]:
# Maruti wali rows Dataset 1 me kaise dikhti hain
print(df1[df1['Make'].str.contains('Maruti', case=False, na=False)][['Make', 'Model', 'match_key']].head(5))

             Make     Model               match_key
52  Maruti Suzuki  S-Presso  maruti suzuki s-presso
53  Maruti Suzuki  S-Presso  maruti suzuki s-presso
54  Maruti Suzuki  S-Presso  maruti suzuki s-presso
55  Maruti Suzuki  S-Presso  maruti suzuki s-presso
56  Maruti Suzuki  S-Presso  maruti suzuki s-presso

In [9]:
# Sirf Model (bina Make ke) use karke naya match_key banao
df1['match_key_v2'] = df1['Model'].str.lower().str.strip()

# Dataset 2: Car_Name se pehla word (brand) hata do, baaki model treat karo
df2['match_key_v2'] = df2['Car_Name'].str.replace(r'^(Maruti Suzuki|Maruti|Tata|Hyundai|Mahindra|Kia|Toyota|Honda|MG|Skoda|Volkswagen|Renault|Nissan|Citroen|Jeep)\s+', '', regex=True, case=False).str.lower().str.strip()

common_v2 = set(df1['match_key_v2']) & set(df2['match_key_v2'])
print("New matching count:", len(common_v2))

New matching count: 57

In [10]:
from rapidfuzz import process, fuzz

# Dataset 1 ka full "Make Model" string (unique list)
df1['full_name'] = (df1['Make'] + ' ' + df1['Model']).str.lower().str.strip()
df1_names = df1['full_name'].unique().tolist()

# Har Dataset 2 car ke liye best match dhoondo Dataset 1 me
def find_best_match(name, choices, threshold=85):
    result = process.extractOne(name, choices, scorer=fuzz.token_sort_ratio)
    if result and result[1] >= threshold:
        return result[0]  # matched name
    return None

df2['matched_full_name'] = df2['match_key'].apply(lambda x: find_best_match(x, df1_names))

matched_count = df2['matched_full_name'].notna().sum()
print(f"Fuzzy matched: {matched_count} out of {len(df2)}")

Fuzzy matched: 82 out of 248

In [12]:
df2['matched_full_name_v2'] = df2['match_key'].apply(
    lambda x: find_best_match(x, df1_names, threshold=88)
)

In [13]:
def find_best_match_v2(name, choices, threshold=88):
    result = process.extractOne(name, choices, scorer=fuzz.token_set_ratio)
    if result and result[1] >= threshold:
        return result[0]
    return None

df2['matched_full_name_v2'] = df2['match_key'].apply(lambda x: find_best_match_v2(x, df1_names))

matched_count_v2 = df2['matched_full_name_v2'].notna().sum()
print(f"Fuzzy matched (v2): {matched_count_v2} out of {len(df2)}")

Fuzzy matched (v2): 152 out of 248

In [14]:
# Sirf wo rows dikhao jo match hue, side-by-side compare karne ke liye
matched_preview = df2[df2['matched_full_name_v2'].notna()][['Car_Name', 'matched_full_name_v2']]
print(matched_preview.to_string())

                            Car_Name                             matched_full_name_v2
0                      Maruti Brezza                      maruti suzuki vitara brezza
2                       Maruti Swift                              maruti suzuki swift
3                       Maruti Dzire                         maruti suzuki dzire tour
4                      Maruti Baleno                             maruti suzuki baleno
6                     Maruti Wagon R                            maruti suzuki r wagon
7                    Maruti Alto K10                           maruti suzuki alto k10
8                      Maruti Ertiga                             maruti suzuki ertiga
9                         Maruti XL6                                maruti suzuki xl6
10                    Maruti Celerio                       maruti suzuki celerio tour
12                      Maruti Ignis                              maruti suzuki ignis
13                   Maruti S-Presso                           maruti suzuki s-presso
14                       Maruti Ciaz                               maruti suzuki ciaz
15                       Maruti Eeco                               maruti suzuki eeco
18                Mahindra Scorpio N                                 mahindra scorpio
20                   Mahindra XUV700                                  mahindra xuv500
22                Mahindra Thar Roxx                                    mahindra thar
23                     Mahindra Thar                                    mahindra thar
25                  Mahindra Scorpio                                 mahindra scorpio
26                   Mahindra Bolero                       mahindra bolero power plus
27               Mahindra Bolero Neo                                  mahindra bolero
28          Mahindra Bolero Neo Plus                                  mahindra bolero
29                   Mahindra XUV400                                  mahindra xuv500
30                  Mahindra Marazzo                                 mahindra marazzo
31                   Tata Harrier EV                                     tata harrier
32                       Tata Altroz                                      tata altroz
33                        Tata Nexon                                       tata nexon
35                      Tata Harrier                                     tata harrier
36                        Tata Tiago                                       tata tiago
38                       Tata Safari                               tata safari storme
40                     Tata Nexon EV                                       tata nexon
42                     Tata Tiago EV                                       tata tiago
43                        Tata Tigor                                    tata tigor ev
44                     Tata Tigor EV                                    tata tigor ev
45                    Tata Tiago NRG                                       tata tiago
46           Tata Harrier EV Stealth                                     tata harrier
47                     Hyundai Creta                                    hyundai creta
49                     Hyundai Venue                                    hyundai venue
50            Hyundai Grand i10 Nios                           hyundai grand i10 nios
51                     Hyundai Verna                                    hyundai verna
52                       Hyundai i20                               hyundai i20 active
53                      Hyundai Aura                                     hyundai aura
55                    Hyundai Tucson                                   hyundai tucson
56            Hyundai Creta Electric                                    hyundai creta
58              Hyundai Creta N Line                                    hyundai creta
60              Hyundai Venue N Line                                    hyundai venue
63                     Toyota Glanza                                    toyota glanza
64                   Toyota Fortuner                                  toyota fortuner
65              Toyota Innova Crysta                             toyota innova crysta
69                      Toyota Camry                                     toyota camry
70          Toyota Fortuner Legender                                  toyota fortuner
72               Toyota Land Cruiser                              toyota land cruiser
73                        Kia Seltos                                       kia seltos
78                      Kia Carnival                                     kia carnival
82                      BMW 5 Series                                     bmw 5-series
83                            BMW X5                                           bmw x5
84                            BMW M5                                           bmw m5
85                            BMW X1                                           bmw x1
86                            BMW X3                                           bmw x3
88                            BMW X7                                           bmw x7
89                            BMW M4                                           bmw m4
90                      BMW 7 Series                                     bmw 7-series
92                            BMW Z4                                  bmw z4 roadster
94                            BMW M2                               bmw m2 competition
99                           BMW iX1                                           bmw x1
100                      BMW X4 M40i                                           bmw x4
106                     Skoda Kodiaq                               skoda kodiaq scout
107  Mercedes-Benz A-Class Limousine              mercedes-benz mercedes-benz a-class
108            Mercedes-Benz G-Class              mercedes-benz mercedes-benz g-class
109                Mercedes-Benz GLC                  mercedes-benz mercedes-benz glc
110                Mercedes-Benz GLA                  mercedes-benz mercedes-benz gle
111            Mercedes-Benz C-Class    mercedes-benz mercedes-benz c-class cabriolet
112            Mercedes-Benz E-Class              mercedes-benz mercedes-benz e-class
113                Mercedes-Benz GLS                  mercedes-benz mercedes-benz gls
114    Mercedes-Benz Maybach S-Class              mercedes-benz mercedes-benz maybach
115                Mercedes-Benz GLE                  mercedes-benz mercedes-benz gle
116            Mercedes-Benz S-Class              mercedes-benz mercedes-benz s-class
117        Mercedes-Benz Maybach GLS              mercedes-benz mercedes-benz maybach
118    Mercedes-Benz AMG GLC43 Coupe  mercedes-benz mercedes-benz amg gt 4-door coupe
119                Mercedes-Benz EQB                  mercedes-benz mercedes-benz gle
120      Mercedes-Benz CLE cabriolet    mercedes-benz mercedes-benz c-class cabriolet
121                Mercedes-Benz EQA                  mercedes-benz mercedes-benz gle
122                Mercedes-Benz EQS                  mercedes-benz mercedes-benz gle
123        Mercedes-Benz AMG G-Class              mercedes-benz mercedes-benz g-class
125     Mercedes-Benz Maybach SL 680              mercedes-benz mercedes-benz maybach
132      Mercedes-Benz AMG GLE Coupe                  mercedes-benz mercedes-benz gle
134    Mercedes-Benz Maybach EQS SUV              mercedes-benz mercedes-benz maybach
139            Mercedes-Benz AMG EQS  mercedes-benz mercedes-benz amg gt 4-door coupe
141                       Honda City                                       honda city
142                      Honda Amaze                                      honda amaze
143              Honda Amaze 2nd Gen                                      honda amaze
144           Honda City Hybrid eHEV                                       honda city
146                        MG Hector                                        mg hector
148                         MG ZS EV                                         mg zs ev
150                   MG Hector Plus                                        mg hector
153                Range Rover Velar                     land rover rover range velar
154                Range Rover Sport                     land rover rover range sport
155                      Range Rover                     land rover rover range sport
156               Range Rover Evoque        land rover rover range evoque convertible
157                  Discovery Sport                       land rover discovery sport
158                        Discovery                             land rover discovery
159                   Renault Triber                                   renault triber
160                     Renault Kwid                                     renault kwid
167                     Jeep Compass                           jeep compass trailhawk
169                    Jeep Wrangler                                    jeep wrangler
170              Jeep Grand Cherokee                              jeep grand cherokee
171                          Audi Q3                                          audi q3
172                          Audi A4                                          audi a4
173                          Audi A6                                          audi a6
174                          Audi Q7                                          audi q7
175                          Audi Q5                                          audi q5
176                Audi S5 Sportback                                          audi s5
177                          Audi Q8                                          audi q8
179                Audi Q3 Sportback                                          audi q3
180                         Audi RS5                                         audi rs5
181           Audi RS Q8 Performance                                          audi q8
182                        Audi A8 L                                        audi a8 l
183         Audi Q8 Sportback e-tron                                          audi q8
184                   Audi Q8 e-tron                                          audi q8
193                       Volvo XC60                                       volvo xc60
194                       Volvo EX40                                       volvo xc40
195                       Volvo XC90                                       volvo xc90
196                       Volvo EC40                                       volvo xc40
197                      Porsche 911                                      porsche 911
198                  Porsche Cayenne                            porsche cayenne coupe
199                    Porsche Macan                                    porsche macan
200                 Porsche Panamera                                 porsche panamera
201                   Porsche Taycan                                    porsche macan
202            Porsche Cayenne Coupe                            porsche cayenne coupe
203           Porsche Macan Turbo EV                                    porsche macan
204                         Lexus ES                                         lexus es
205                         Lexus LX                                    lexus lx 450d
206                         Lexus NX                                    lexus nx 300h
208                         Lexus RX                                    lexus rx 450h
209              Lamborghini Urus SE                                 lamborghini urus
212                    Jaguar F-Pace                                    jaguar f-pace
213              Rolls-Royce Phantom          mercedes-benz rolls-royce phantom coupe
214             Rolls-Royce Cullinan               mercedes-benz rolls-royce cullinan
216                      MINI Cooper                               mini cooper 3 door
217                  MINI Countryman                                  mini countryman
218                   MINI Cooper SE                               mini cooper 3 door
219         MINI Countryman Electric                                  mini countryman
224                Ferrari Portofino                                ferrari portofino
226              Force Motors Gurkha                                     force gurkha
228                    Isuzu V-Cross                               isuzu dmax v-cross
229                       Isuzu MU-X                                       isuzu mu-x
230                  Maserati Ghibli                                  maserati ghibli
232                 Maserati Levante                                 maserati levante
233            Maserati Quattroporte                            maserati quattroporte
235             Maserati GranTurismo                             maserati granturismo
238             Aston Martin Vantage                             aston martin vantage
239                 Aston Martin DBX                               aston martin db 11
241                 Bentley Bentayga                                 bentley bentayga

In [15]:
import re

def has_conflict(name1, name2):
    # Rule 1: agar dono me numbers hain, wo match hone chahiye
    nums1 = set(re.findall(r'\d+', name1))
    nums2 = set(re.findall(r'\d+', name2))
    if nums1 and nums2 and nums1 != nums2:
        return True
    
    # Rule 2: EV/Electric keyword sirf ek taraf hona chahiye ni
    ev_keywords = ['electric', ' ev', 'e-tron', 'eq', 'ix', ' se']
    name1_has_ev = any(k in f' {name1} ' for k in ev_keywords)
    name2_has_ev = any(k in f' {name2} ' for k in ev_keywords)
    if name1_has_ev != name2_has_ev:
        return True
    
    return False

# Conflict check lagao existing matches pe
df2['has_conflict'] = df2.apply(
    lambda row: has_conflict(str(row['Car_Name']).lower(), str(row['matched_full_name_v2'])) 
    if pd.notna(row['matched_full_name_v2']) else False, 
    axis=1
)

print("Conflicts found:", df2['has_conflict'].sum())
print(df2[df2['has_conflict']][['Car_Name', 'matched_full_name_v2']].to_string())

Conflicts found: 24
                          Car_Name                             matched_full_name_v2
20                 Mahindra XUV700                                  mahindra xuv500
29                 Mahindra XUV400                                  mahindra xuv500
31                 Tata Harrier EV                                     tata harrier
40                   Tata Nexon EV                                       tata nexon
42                   Tata Tiago EV                                       tata tiago
43                      Tata Tigor                                    tata tigor ev
46         Tata Harrier EV Stealth                                     tata harrier
56          Hyundai Creta Electric                                    hyundai creta
82                    BMW 5 Series                                     bmw 5-series
90                    BMW 7 Series                                     bmw 7-series
99                         BMW iX1                                           bmw x1
100                    BMW X4 M40i                                           bmw x4
118  Mercedes-Benz AMG GLC43 Coupe  mercedes-benz mercedes-benz amg gt 4-door coupe
119              Mercedes-Benz EQB                  mercedes-benz mercedes-benz gle
121              Mercedes-Benz EQA                  mercedes-benz mercedes-benz gle
122              Mercedes-Benz EQS                  mercedes-benz mercedes-benz gle
134  Mercedes-Benz Maybach EQS SUV              mercedes-benz mercedes-benz maybach
139          Mercedes-Benz AMG EQS  mercedes-benz mercedes-benz amg gt 4-door coupe
183       Audi Q8 Sportback e-tron                                          audi q8
184                 Audi Q8 e-tron                                          audi q8
203         Porsche Macan Turbo EV                                    porsche macan
209            Lamborghini Urus SE                                 lamborghini urus
218                 MINI Cooper SE                               mini cooper 3 door
219       MINI Countryman Electric                                  mini countryman

In [16]:
def has_conflict_v2(name1, name2):
    nums1 = set(re.findall(r'\d+', name1))
    nums2 = set(re.findall(r'\d+', name2))
    if nums1 and nums2 and nums1 != nums2:
        return True
    
    # \b use karo taaki "series" ke andar "se" match na ho
    ev_pattern = r'\b(electric|ev|e-tron|eq[a-z]?|ix\d|urus se)\b'
    name1_has_ev = bool(re.search(ev_pattern, name1))
    name2_has_ev = bool(re.search(ev_pattern, name2))
    if name1_has_ev != name2_has_ev:
        return True
    
    return False

df2['has_conflict_v2'] = df2.apply(
    lambda row: has_conflict_v2(str(row['Car_Name']).lower(), str(row['matched_full_name_v2'])) 
    if pd.notna(row['matched_full_name_v2']) else False, 
    axis=1
)

print("Conflicts (v2):", df2['has_conflict_v2'].sum())
print(df2[df2['has_conflict_v2']][['Car_Name', 'matched_full_name_v2']].to_string())

Conflicts (v2): 21
                          Car_Name                             matched_full_name_v2
20                 Mahindra XUV700                                  mahindra xuv500
29                 Mahindra XUV400                                  mahindra xuv500
31                 Tata Harrier EV                                     tata harrier
40                   Tata Nexon EV                                       tata nexon
42                   Tata Tiago EV                                       tata tiago
43                      Tata Tigor                                    tata tigor ev
46         Tata Harrier EV Stealth                                     tata harrier
56          Hyundai Creta Electric                                    hyundai creta
99                         BMW iX1                                           bmw x1
100                    BMW X4 M40i                                           bmw x4
118  Mercedes-Benz AMG GLC43 Coupe  mercedes-benz mercedes-benz amg gt 4-door coupe
119              Mercedes-Benz EQB                  mercedes-benz mercedes-benz gle
121              Mercedes-Benz EQA                  mercedes-benz mercedes-benz gle
122              Mercedes-Benz EQS                  mercedes-benz mercedes-benz gle
134  Mercedes-Benz Maybach EQS SUV              mercedes-benz mercedes-benz maybach
139          Mercedes-Benz AMG EQS  mercedes-benz mercedes-benz amg gt 4-door coupe
183       Audi Q8 Sportback e-tron                                          audi q8
184                 Audi Q8 e-tron                                          audi q8
203         Porsche Macan Turbo EV                                    porsche macan
209            Lamborghini Urus SE                                 lamborghini urus
219       MINI Countryman Electric                                  mini countryman

In [17]:
# Guard ne jo pakde (genuine EV/spec conflicts)
auto_excluded = df2[df2['has_conflict_v2']]['Car_Name'].tolist()

# Guard se bach gaye, manually dekhe hue galat matches
manual_exclude = ['Range Rover', 'Porsche Taycan', 'Aston Martin DBX']

all_excluded = set(auto_excluded) | set(manual_exclude)
print("Total excluded:", len(all_excluded))

# Final clean matched dataset — sirf wahi rows rakho jo match hue AUR exclude list me nahi
df2_clean = df2[
    df2['matched_full_name_v2'].notna() & 
    ~df2['Car_Name'].isin(all_excluded)
].copy()

print("Final clean matched rows:", len(df2_clean))

Total excluded: 24
Final clean matched rows: 128

In [18]:
# df2_clean me se sirf zaroori columns lo merge ke liye
df2_to_merge = df2_clean[['matched_full_name_v2', 'Rating', 'Safety_Stars', 'Mileage_kmpl', 'Sales_FY2024']].copy()
df2_to_merge = df2_to_merge.rename(columns={'matched_full_name_v2': 'full_name'})

# df1 (specs) ke saath left-merge karo — df1 ki saari rows preserve rahengi
df_merged = df1.merge(df2_to_merge, on='full_name', how='left')

print("Merged shape:", df_merged.shape)
print()
print("Rows with mileage data:", df_merged['Mileage_kmpl'].notna().sum())
print("Rows with safety data:", df_merged['Safety_Stars'].notna().sum())
print()
df_merged.head()

Merged shape: (1403, 23)

Rows with mileage data: 477
Rows with safety data: 575

,Make,Model,Variant,Ex-Showroom_Price,Displacement,Cylinders,Fuel_Tank_Capacity,Fuel_Type,Height,Length,...,Type,Power.1,Torque.1,match_key,match_key_v2,full_name,Rating,Safety_Stars,Mileage_kmpl,Sales_FY2024
0,Hyundai,Santro,Era Mt,"₹ 429,990.000000000000000",1086,4,35.0,Petrol,1560,3610.0,...,Manual,69.0,99.04,hyundai santro,santro,hyundai santro,NaN,NaN,NaN,NaN
1,Hyundai,Santro,Magna Mt,"₹ 503,990.000000000000000",1086,4,35.0,Petrol,1560,3610.0,...,Manual,69.0,99.04,hyundai santro,santro,hyundai santro,NaN,NaN,NaN,NaN
2,Hyundai,Santro,Magna Mt Cng,"₹ 547,990.000000000000000",1086,4,35.0,CNG,1560,3610.0,...,Manual,59.0,99.04,hyundai santro,santro,hyundai santro,NaN,NaN,NaN,NaN
3,Hyundai,Santro,Magna Amt,"₹ 530,990.000000000000000",1086,4,35.0,Petrol,1560,3610.0,...,AMT,69.0,10.10,hyundai santro,santro,hyundai santro,NaN,NaN,NaN,NaN
4,Hyundai,Santro,Sportz Mt,"₹ 512,990.000000000000000",1086,4,35.0,Petrol,1560,3610.0,...,Manual,69.0,10.10,hyundai santro,santro,hyundai santro,NaN,NaN,NaN,NaN

In [19]:
# Check karo kya full_name duplicate hai matched dataset me
dup_check = df2_to_merge['full_name'].value_counts()
duplicates = dup_check[dup_check > 1]
print("Duplicate full_names:", len(duplicates))
print(duplicates)

Duplicate full_names: 19
full_name
mercedes-benz mercedes-benz gle                  3
mercedes-benz mercedes-benz maybach              3
mahindra scorpio                                 2
mahindra thar                                    2
mahindra bolero                                  2
tata tiago                                       2
hyundai creta                                    2
hyundai venue                                    2
toyota fortuner                                  2
mercedes-benz mercedes-benz g-class              2
mercedes-benz mercedes-benz c-class cabriolet    2
honda city                                       2
honda amaze                                      2
mg hector                                        2
audi q3                                          2
audi q8                                          2
volvo xc40                                       2
porsche cayenne coupe                            2
mini cooper 3 door                               2
Name: count, dtype: int64

In [20]:
# Dedup: duplicate full_name me se pehli row rakho
df2_to_merge_dedup = df2_to_merge.drop_duplicates(subset='full_name', keep='first')
print("Before dedup:", len(df2_to_merge), "After dedup:", len(df2_to_merge_dedup))

# Merge dobara karo, dedup wale data se
df_merged = df1.merge(df2_to_merge_dedup, on='full_name', how='left')

print()
print("Merged shape:", df_merged.shape)
print("Rows with mileage data:", df_merged['Mileage_kmpl'].notna().sum())
print("Rows with safety data:", df_merged['Safety_Stars'].notna().sum())

Before dedup: 128 After dedup: 107

Merged shape: (1276, 23)
Rows with mileage data: 389
Rows with safety data: 476

In [21]:
# Price: ₹ symbol, commas, extra decimals hatao, number banao
df_merged['Price'] = (
    df_merged['Ex-Showroom_Price']
    .astype(str)
    .str.replace('₹', '', regex=False)
    .str.replace(',', '', regex=False)
    .str.strip()
    .astype(float)
)

# Columns ko clean, meaningful naam do
df_merged = df_merged.rename(columns={
    'Make': 'brand',
    'Model': 'model',
    'Variant': 'variant',
    'Price': 'price',
    'Displacement': 'engine_cc',
    'Fuel_Type': 'fuel_type',
    'Body_Type': 'body_type',
    'Seating_Capacity': 'seating_capacity',
    'Type': 'transmission',
    'Power.1': 'power_bhp',
    'Torque.1': 'torque_nm',
    'Mileage_kmpl': 'mileage',
    'Safety_Stars': 'safety_rating',
    'Ground_Clearance': 'ground_clearance'  # agar exist kare
})

# Check karo price sahi ban gaya
print(df_merged[['brand', 'model', 'variant', 'price', 'fuel_type', 'transmission', 'mileage', 'safety_rating']].head(10))
print()
print("Price stats:")
print(df_merged['price'].describe())

     brand   model        variant     price fuel_type transmission  mileage  \
0  Hyundai  Santro         Era Mt  429990.0    Petrol       Manual      NaN
1  Hyundai  Santro       Magna Mt  503990.0    Petrol       Manual      NaN
2  Hyundai  Santro   Magna Mt Cng  547990.0       CNG       Manual      NaN
3  Hyundai  Santro      Magna Amt  530990.0    Petrol          AMT      NaN
4  Hyundai  Santro      Sportz Mt  512990.0    Petrol       Manual      NaN
5  Hyundai  Santro  Sportz Mt Cng  578990.0       CNG       Manual      NaN
6  Hyundai  Santro     Sportz Amt  570990.0    Petrol          AMT      NaN
7  Hyundai  Santro        Asta Mt  556490.0    Petrol       Manual      NaN
8     Tata   Tiago    Revotron Xe  460000.0    Petrol       Manual     23.5
9  Hyundai    Aura   E 1.2 Petrol  579900.0    Petrol       Manual      NaN

   safety_rating
0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
5            NaN
6            NaN
7            NaN
8            4.0
9            2.0

Price stats:
count    1.276000e+03
mean     4.596538e+06
std      1.214735e+07
min      2.364470e+05
25%      7.438760e+05
50%      1.060064e+06
75%      2.979828e+06
max      2.121554e+08
Name: price, dtype: float64

In [22]:
# Pehle dekho kitna missing hai body_type ke hisaab se
print("Missing mileage %:")
print(df_merged.groupby('body_type')['mileage'].apply(lambda x: x.isna().mean() * 100).round(1))
print()
print("Missing safety_rating %:")
print(df_merged.groupby('body_type')['safety_rating'].apply(lambda x: x.isna().mean() * 100).round(1))

Missing mileage %:
body_type
Convertible             85.0
Convertible, Coupe     100.0
Convertible, Sports      0.0
Coupe                   85.4
Coupe, Sedan           100.0
Crossover              100.0
Crossover, SUV           0.0
Crossover, Sedan       100.0
Hatchback               68.0
Hatchback, Sports      100.0
MPV                     41.0
MUV                     66.7
Not Mentioned           16.7
Pick-up                100.0
SUV                     66.2
Sedan                   76.0
Sports                  66.7
Name: mileage, dtype: float64

Missing safety_rating %:
body_type
Convertible             85.0
Convertible, Coupe     100.0
Convertible, Sports      0.0
Coupe                   85.4
Coupe, Sedan           100.0
Crossover              100.0
Crossover, SUV           0.0
Crossover, Sedan       100.0
Hatchback               60.4
Hatchback, Sports      100.0
MPV                     41.0
MUV                     38.5
Not Mentioned           16.7
Pick-up                  0.0
SUV                     54.4
Sedan                   77.2
Sports                  66.7
Name: safety_rating, dtype: float64

In [23]:
# body_type ko simplify: comma ke baad wala hata do (sirf pehla/primary type rakho)
df_merged['body_type_clean'] = df_merged['body_type'].astype(str).str.split(',').str[0].str.strip()

print(df_merged['body_type_clean'].value_counts())

body_type_clean
SUV              447
Sedan            333
Hatchback        317
Coupe             43
MPV               39
MUV               39
Convertible       23
Crossover         23
Not Mentioned      6
Sports             3
Pick-up            3
Name: count, dtype: int64

In [24]:
# Step A: per body_type_clean median se fill karne ki koshish
df_merged['mileage'] = df_merged.groupby('body_type_clean')['mileage'].transform(
    lambda x: x.fillna(x.median())
)
df_merged['safety_rating'] = df_merged.groupby('body_type_clean')['safety_rating'].transform(
    lambda x: x.fillna(x.median())
)

# Step B: jo abhi bhi NaN bache (poora group hi missing tha), unhe overall median se fill karo
df_merged['mileage'] = df_merged['mileage'].fillna(df_merged['mileage'].median())
df_merged['safety_rating'] = df_merged['safety_rating'].fillna(df_merged['safety_rating'].median())

print("Remaining missing mileage:", df_merged['mileage'].isna().sum())
print("Remaining missing safety:", df_merged['safety_rating'].isna().sum())

Remaining missing mileage: 0
Remaining missing safety: 0

In [25]:
# Track karo kaunsi rows imputed thi (asli merge se pehle NaN thi)
# Note: humne already overwrite kar diya hai, isliye ye flag pehle hi bana lena chahiye tha —
# lekin humare paas abhi bhi 'df2_to_merge_dedup' se pata chal sakta hai kaunsi rows match hui thi

df_merged['mileage_is_imputed'] = ~df_merged['full_name'].isin(df2_to_merge_dedup['full_name'])
df_merged['safety_is_imputed'] = df_merged['mileage_is_imputed']  # same source, same flag

print("Imputed mileage rows:", df_merged['mileage_is_imputed'].sum())
print("Real mileage rows:", (~df_merged['mileage_is_imputed']).sum())

Imputed mileage rows: 728
Real mileage rows: 548

In [26]:
final_columns = [
    'brand', 'model', 'variant', 'price', 'fuel_type', 'transmission',
    'engine_cc', 'power_bhp', 'torque_nm', 'seating_capacity',
    'body_type_clean', 'mileage', 'safety_rating',
    'mileage_is_imputed', 'safety_is_imputed'
]

df_final = df_merged[final_columns].rename(columns={'body_type_clean': 'body_type'})

# Save karo processed folder me
df_final.to_csv('../data/processed/cars_processed.csv', index=False)

print("Saved! Final shape:", df_final.shape)
df_final.head()

Saved! Final shape: (1276, 15)

,brand,model,variant,price,fuel_type,transmission,engine_cc,power_bhp,torque_nm,seating_capacity,body_type,mileage,safety_rating,mileage_is_imputed,safety_is_imputed
0,Hyundai,Santro,Era Mt,429990.0,Petrol,Manual,1086,69.0,99.04,5,Hatchback,26.0,2.0,True,True
1,Hyundai,Santro,Magna Mt,503990.0,Petrol,Manual,1086,69.0,99.04,5,Hatchback,26.0,2.0,True,True
2,Hyundai,Santro,Magna Mt Cng,547990.0,CNG,Manual,1086,59.0,99.04,5,Hatchback,26.0,2.0,True,True
3,Hyundai,Santro,Magna Amt,530990.0,Petrol,AMT,1086,69.0,10.10,5,Hatchback,26.0,2.0,True,True
4,Hyundai,Santro,Sportz Mt,512990.0,Petrol,Manual,1086,69.0,10.10,5,Hatchback,26.0,2.0,True,True

In [27]:
notes = """
# Phase 1 — Dataset Preprocessing Notes
...
"""
with open('../data/processed/preprocessing_notes.md', 'w') as f:
    f.write(notes)
print("Notes saved!")

Notes saved!

In [28]:
import os
print(os.listdir('../data/processed/'))

['preprocessing_notes.md', 'cars_processed.csv']